name: Subdomain Recon Workflow

on:
  push:
    branches:
      - main

jobs:
  subdomain-recon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
          
      - name: Install subfinder
        run: go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
      
      - name: Install httprobe
        run: go install github.com/tomnomnom/httprobe@latest
      
      - name: Install nuclei
        run: GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
      
      - name: Find subdomains
        run: subfinder -d example.com -o subdomains.txt
      
      - name: Find live URLs
        run: cat subdomains.txt | httprobe | tee urls.txt
      
      - name: Run nuclei on live URLs
        run: cat urls.txt | nuclei -t ~/nuclei-templates/ -o report.txt
      
      - name: Create GitHub issue
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Nuclei Report for example.com
          body: |
            Please find the Nuclei report for example.com in the attachment.
          labels: report
          assignees: ${{ github.actor }}
          milestone: '1'
          file-path: report.txt
